version: '3'

services:
  fastapi:
    image: image-fastapi

    build: .

    container_name: fastapi-aplicacion

    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/app
